### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by roo12312** [maggialejandro/agenda-react-native#2]
How to use? any guides?

**Comment by maggialejandro** [comment]
Hi @rohankm 
Take a look at the example App
https://github.com/maggialejandro/agenda-react-native/blob/60b7289e35c3c79bcb6efed50ce7d182bf0b8e33/example/App.tsx#L92-L97

Available prop are here
https://github.com/maggialejandro/agenda-react-native/blob/60b7289e35c3c79bcb6efed50ce7d182bf0b8e33/src/types.ts#L51-L69

**Comment by ramiro-e** [comment]
Hi ale, what are the theme types? is there a way to hide the calendar?

**Comment by maggialejandro** [comment]
> Hi ale, what are the theme types? is there a way to hide the calendar?

Hi Ramiro, you could use any value other than `week` or `month` on `viewType` prop and ignore the ts error.
Feel free to remove the default value and create a PR if you want
